version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bforbank_test_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
